### ISSUE TITLE
It doesn't work on x86_64

### ISSUE THREAD

**Issue by citypw** [shaded-enmity/r2-ropstats#1]
./gadget-stats /usr/lib/libcr.so.0
[-] Opening file:   "/usr/lib/libcr.so.0" 
   ✓ Analyzing ... 
   ➙ ----------------------------------------------------------------------
Traceback (most recent call last):
  File "./gadget-stats", line 36, in <module>
    print (u"   ➙ Entrypoint: %s" % (pptr(core.num.get ("entry0"))))
  File "./gadget-stats", line 20, in pptr
    return '0x%08x' % int(x, 16)
TypeError: int() can't convert non-string with explicit base

**Comment by shaded-enmity** [comment]
Should be fixed now. Thank you for the report.
