### ISSUE TITLE
Rewrite on r2pipe

### ISSUE THREAD

**Issue by dukebarman** [shaded-enmity/r2-ropstats#2]
Radare2 Team recommend use r2pipe instead of radare2 bindings

**Comment by shaded-enmity** [comment]
@dukebarman I haven't used r2 for a quite some time and have no idea about the new APIs, can you please send a pull request with the required changes?

**Comment by dukebarman** [comment]
@shaded-enmity example with new API https://github.com/radare/radare2-bindings/tree/master/r2pipe/python

**Comment by shaded-enmity** [comment]
@dukebarman hmm, looks pretty simple, do you know what command would be equivalent to the `core.anal_all()` [call](https://github.com/shaded-enmity/r2-ropstats/blob/master/gadget-stats#L34)? I'm guessing `aaf` would suffice but don't really have time to play with it right now.

**Comment by dukebarman** [comment]
@shaded-enmity `aaaa`

**Comment by shaded-enmity** [comment]
@dukebarman thanks, updates pushed to master

**Comment by dukebarman** [comment]
And thank you!
